Repository rrabinovitch/Crate, pull requests merged in 2020-10, with the labels that each got.

#34 Create style page, create route to style page
  code/api/package-lock.json
  code/web/package-lock.json
  code/web/src/modules/crate/Item.js
  code/web/src/modules/survey/Survey.js
  code/web/src/modules/user/api/state.js
  code/web/src/setup/routes/crate.js
Labels: enhancement, fe

#40 Tm/add submit functionality
  code/web/public/surveyImages/index.js
  code/web/src/modules/survey/Survey.js
Labels: bug, enhancement, fe

#45 Add ability to submit user style
  code/api/src/modules/user/resolvers.js
  code/mobile/src/setup/index.js
  code/web/src/modules/survey/Survey.js
  code/web/src/modules/survey/api.js
  code/web/src/modules/user/api/state.js
Labels: be, bug, enhancement, fe

#35 Reducer testing
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/survey/api/actions.js
  code/web/src/modules/user/StyleModal.js
  code/web/src/modules/user/api/state.test.js
Labels: bug, fe

#48 Add images for style survey
  code/web/.DS_Store
  code/web/public/.DS_Store
  code/web/public/surveyImages/.DS_Store
  code/web/public/surveyImages/index.js
  code/web/public/surveyImages/scary/scary-pants.jpeg
  code/web/public/surveyImages/scary/scary-shoes.jpg
  code/web/public/surveyImages/scary/scary-spice.jpg
  code/web/public/surveyImages/scary/wig.jpg
  code/web/src/modules/survey/api.js
  code/web/src/modules/user/api/state.js
Labels: fe
